### ISSUE TITLE
Why using apply method is necessary to solve exercise 10?

### ISSUE THREAD

**Issue by segmentationfaulter** [ReactiveX/learnrx#101]
I implemented `concatAll()` method in the following way and it is marked to be correct by your tutorial.
```js
Array.prototype.concatAll = function() {
	var results = [];
	this.forEach(function(subArray) {
            subArray.forEach(function(element) {
    	    results.push(element);
        });
	});

	return results;
};
```
but when I clicked on 'Show Answer', it was using `apply` method on `push`, I was wondering why it was needed to use `apply` method given it works fine without it?

**Comment by thisisandrew** [comment]
`apply` receives the second argument as an `array` but `apply` passes each member of the array into `push` as a separate argument. `push` appends any arguments to the array it is called on.
