### ISSUE TITLE
Revise lesson 36 and onward for the RxJS 5 API

### ISSUE THREAD

**Issue by ghost** [ReactiveX/learnrx#157]
Hello there,

First of all, thank you for producing these practical lessons. They have been a very useful introduction to the thought process for reactive programming.

After I reached lesson 36, I noticed that running the lesson code didn't result in JSON data being returned successfully. Instead, I was seeing:

![image](https://cloud.githubusercontent.com/assets/2031402/20460173/dce4e3fc-af16-11e6-8755-f2695a71ceaa.png)

I dug into this a bit and eventually came to the conclusion that the lesson code was assuming an RxJS 4.x API. In RxJS 5, [`forEach`](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-forEach) no longer takes three functions corresponding to the next, error and complete states. This might explain why I was seeing the alert above (i.e. the promise constructor).

My guess at fixing this problem would be to switch over to `subscribe` and update the code to use the [new Observable interface](https://github.com/ReactiveX/rxjs/blob/836fb1f9e99dfa9a86e9d180d0b50c73dee78b50/MIGRATION.md#observer-interface-changes-also-subjects).

Furthermore, the `throttle` function has been renamed to `throttleTime`, which renders some of the later lessons unusable too.

I'm happy to do a pull request to fix these things, but I wanted to check the intent of the existing lessons beforehand.

**Comment by jesusreal** [comment]
I just finished the tutorial. +1 regarding the throttle method. Also for the "scan" operator the order of the arguments has to be updated. I would also be happy to create a pull request for these 2 issues.

**Comment by morenoh149** [comment]
@jesusreal it'd be welcome

**Comment by jesusreal** [comment]
Thanks @miqid for taking the time to do a pr for the issues. As the pull request got merged almost two months ago, I think this ticket should be closed :)

**Comment by thw0rted** [comment]
I'm still having these issues on `http://reactivex.io/learnrx/` -- is this tracker the right place to discuss that version of the site?  Is there a better place to try the latest-and-greatest version?

**Comment by morenoh149** [comment]
@thw0rted this is the issue tracker for that site. Feel free to open new issues for new issues or add new info on existing issues.
