### ISSUE TITLE
Exercise 23 - broken?

### ISSUE THREAD

**Issue by lanaebk** [ReactiveX/learnrx#166]
The program won't accept even the provided answer for exercise 23. "Show answer" provides this code: 	
```
return Array.
		zip(
		  videos,
		  bookmarks,
		  function(video, bookmark) {
			return {videoId: video.id, bookmarkId: bookmark.id};
		  });
```
However, pressing "Run" pops up this error message: 
![image](https://user-images.githubusercontent.com/9276095/29137608-e9ebb384-7d0e-11e7-8f53-293116200aca.png)

Using Chrome 60.0.3112.90 on Mac OSX

**Comment by aariabov** [comment]
You need press "Show Answer" and then press "Run" on Exercise 22.
Then Exercise 23 will work.

**Comment by morenoh149** [comment]
@lanaebk did that work?

**Comment by seanpoulter** [comment]
I'd suggest this issue can be closed. We haven't heard anything in a while and I've confirmed the code from @lanaebk works today:

![reactivex - learnrx - 166](https://user-images.githubusercontent.com/2585460/53971069-19af4880-40ca-11e9-884d-a96dc02259be.gif)
