### ISSUE TITLE
rx library implementation?

### ISSUE THREAD

**Issue by vittod** [ReactiveX/learnrx#171]
I just tried to pick up my exercises in this great training tool and can't get past exercise 3. 
My console tells me theres a problem loading the RX recources.

**Comment by thoFurman** [comment]
You can run the page local if change the index.html in line 5043 from 
<script src="https://unpkg.com/@reactivex/rxjs/dist/global/Rx.js"></script> to 
<script src="https://unpkg.com/@reactivex/rxjs@5.5.5/dist/global/Rx.js"></script>. 
This worked for me until they change the resources online.

**Comment by harveysanders** [comment]
+1
FYI:
`GET to  https://unpkg.com/@reactivex/rxjs@6.0.0/dist/global/Rx.js` responds with
"Cannot find module "/dist/global/Rx.js" in package @reactivex/rxjs@6.0.0"

**Comment by seanpoulter** [comment]
This is a duplicate of #173 which can also be closed. It was resolved by PR #170.
