### ISSUE TITLE
The online site is not working after cancel the "Set answer JSON" promt :(

### ISSUE THREAD

**Issue by deepakshrma** [ReactiveX/learnrx#95]
I tried to open it on my chrome browser. It is not working at all. I press run button too many times.. Nothing happens. I did some changes on code. it throws me error all the time. Even though i copied answer from other location. I clicked on `show all answer` nothing happens. I thought i is the prob with chome. I tried it on Firefoz though, Result is same. Run still not woking. Somehow show all works on firefox. But excep that nothing is working. Please check. I have mention all required detail below. Examples are too good. Thanks :+1: 

Google Chrome
Version 43.0.2357.81 unknown (64-bit)  
Firefox
38.0
System:
Ubuntu LTS 14.04

![functional programming in javascript](https://cloud.githubusercontent.com/assets/7682731/10268681/ca7c9f1c-6add-11e5-912d-51b93eddd6cd.png)

**Comment by deepakshrma** [comment]
Hi!! i have got the cause of the bug. Due to my curiosity, I pressed every button which leads to set newStatus null. I have fixed and created a pull request. Please check.
#95

**Comment by seanpoulter** [comment]
I think we can close this issue as well @morenoh149.
It looks like @deepakshrma has 3 PRs related to improving the modal. 👍
